import Footer from "@/components/Footer/Footer";
import { Inter } from "next/font/google";
import "./globals.css";

// Load the Inter font with the "latin" subset
const inter = Inter({ subsets: ["latin"] });

// Metadata for the layout: tab title and html description
export const metadata = {
  title: "MENU SWIPER",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // Set the language of the HTML document
    <html lang="en">
      {/* Apply the Inter font to the body */}
      <body className={inter.className}>
        {/* Create a container with minimum height of the screen */}
        <div className="min-h-screen">
          {/* Render the children components */}
          {children}
          {/* Render the Footer component */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
